#server
#server:
#  host: 39.98.219.33
#  port: 8003
#  servlet:
#    context-path: /words

server:
  host: 39.98.219.33
  port: 8003
  servlet:
    context-path: /words

#netty
#netty:
#  host: 172.16.1.233
#  port: 9090
#
#netty:
#  host: 47.107.67.75
#  port: 9090

# 禁用缓存
spring:
  # 配置 thymeleaf 在开发环境禁用缓存
  thymeleaf:
    cache: false
  # 数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/words?characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    # 配置数据库连接池
    druid:
      initial-size: 50
      max-active: 1000
      min-idle: 50
      max-wait: 60000
  jpa:
    database: MYSQL
    show-sql: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss



#分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#mybatis&&通用Mapper
mybatis:
  type-aliases-package: com.zcf.words.entity
  mapper-locations: classpath:mapper/*.xml
mapper:
  mappers: com.zcf.words.common.mybatis.MyMapper
  identity: MYSQL

# 本地文件映射的url路径
# 映射图片资源绝对路径
#静态资源对外暴露的访问路径
file:
    staticAccessPath: upload/**
      #文件上传目录（注意Linux和Windows上的目录结构不同）
      #file.uploadFolder=/home/upload/
      #uploadFolder: c://upload/
    uploadFolder: /home/upload/




